### ISSUE TITLE
Unable to decode LocateReplyMessage

### ISSUE THREAD

**Issue by mmendeza** [AlvaroVega/TIDorbJ#2]
The method receiveBody of class GIOPLocateReplyMessage  does not get called from Connection.

It should be     
`public void receiveBody(Connection conn, byte[] header_bytes)`
instead of
`public void receiveBody(IIOPConnection conn, byte[] header_bytes)`

**Comment by AlvaroVega** [comment]
Thanks, a PR to fix it was done: https://github.com/AlvaroVega/TIDorbJ/pull/3
